### PR TITLE
Fix for bug #30 and Has label filter for Out step

### PR DESCRIPTION
**Pull request by vemuripavan**

### CODE REVIEW

**Comment by BenjaBobs** [comment]
Nice job. I do have a comment for the label-step though. I encountered this problem (having multiple edges with the same name) and found that the traversal still includes all the edges and entities.
So while this indeed will do the job, if you have the following scenario:
```c#
class A : IVertex
{
	public EdgeToB Edge1 { get; set; }
	public EdgeToC Edge2 { get; set; }
}

[Label("edge")]
class EdgeToB : IEdge
{
}

[Label("edge")]
class EdgeToC : IEdge
{
}
```
And you have a vertex `A` that has 999 edges to `B` and 1 edge to `C`, you will find that `A.Out('edge').hasLabel('C')` will cost ~1000 RU (iirc) since Cosmos has to check and read all edges before it can start filtering on vertex level.
The optimal solution would instead be having the check on the edge itself, e.g. `A.OutE('edge').has('InVLabel', 'C').InV()`, which would cost ~2 RU.
However, since Cosmos doesn't index any of the native edge properties as searchable, you'd have to explicitly duplicate those so they are stored in Cosmos as edge properties and will then be searchable.
Something like this:
```c#
class FilterableEdge<TOut, TIn> : ManyToManyEdge<TOut, TIn>
	where TOut : IVertex
	where TIn : IVertex
{
	public string OutVLabel => LabelNameResolver.GetLabelName(typeof(TOut));
	public string InVLabel => LabelNameResolver.GetLabelName(typeof(TIn));
}
```
I think maybe there should be a design discussion on how to best tackle this issue.

**Comment by evo-terren** [comment]
I'm a little confused as to what this has to do with #30. Did you mean to refer to a different issue?

Regardless, I never meant for this project to become any sort of framework on top of the Gremlin query language because that will definitely open up a can of worms that I'm not ready to take on in this codebase. More specifically what I mean is that if a user of this library uses the `Out()` method in c#, I think it should only ever result in the `out()` step in Gremlin, not `out().has()`. I don't want future users of the library to be confused where extra steps are coming from (especially if they could have a negative performance impact).

**Comment by vemuripavan** [comment]
@evo-terren I am really thankful to you for creating this library, It is very helpful to me. I am new Gremlin and Graph API, you provided a smooth track for starters like me.

Sorry, For creating confusion by creating a pull request together addressing different issues.
The commit https://github.com/evo-terren/Gremlin.Net.CosmosDb/pull/42/commits/220a58a98e6c9dcf14d9557fdc4973cdf36ed03d should address the issue #30. It worked for me.

**Comment by vemuripavan** [comment]
Coming to "out().has()" part I understood your intention and I do agree with you on performance part.
But In the case like I have shared where edge with same created with different out edges,  

    [Label("product")]
    public sealed class ProductVertex : IVertex
    {
        public string Id { get; set; }
        public PersonPurchasedProductEdge People { get; set;  }
        public StorePurchasedProductEdge Store { get; set; }
    }

    [Label("purchased")]
    public sealed class PersonPurchasedProductEdge : ManyToManyEdge<PersonVertex, ProductVertex>
    {
        public string Id { get; set; }
    }

    [Label("purchased")]
    public sealed class StorePurchasedProductEdge : ManyToManyEdge<StoreVertex, ProductVertex>
    {
        public string Id { get; set; }
    }

In this case, both of the below queries returning same result,
var storesPurchasedProduct = g.V<ProductVertex>("id").In(c => c.Store);
var personsPurchasedProduct = g.V<ProductVertex>("id").In(c => c.People);

Which is not something expected, Same case happening with Out as well.

At the same time I totally agree with you the additional step it is going to create and performance hit.
But I can come up with a better solution considering the design suggestions given by @BenjaBobs, so that the additional step comes into picture only when it is required (where there is a shared edge).

Let me know your thoughts.

Thank you @evo-terren  and @BenjaBobs

**Comment by BenjaBobs** [comment]
An option could be to create an analyzer that emits a warning if an `IVertex` has multiple edges with the same name.

**Comment by BenjaBobs** [comment]
Sadly, I have zero experience writing analyzers, but I hear it's been made significantly easier since the release of Roslyn. I don't have the time though.
https://docs.microsoft.com/en-us/visualstudio/extensibility/getting-started-with-roslyn-analyzers?view=vs-2017

**Comment by jpamp** [comment]
I agree that the extra step should not be "hidden" in the library.  But an extension method to add the extra step could easily be added by anyone who did desire that behavior.  My team has added a few "steps" that way based on our needs.

**Comment by evo-terren** [comment]
I'm going to go ahead and make an executive decision here and say that I would not like for this to be part of the code base due to the concerns we've all discussed above. I recommend you either add a custom extension method in your own code or change your label names so that they are unique across different types of edges.

**Comment by vemuripavan** [comment]
Yeah, I can go with adding custom extension method. Thanks for all you inputs.
Any thought on commit https://github.com/evo-terren/Gremlin.Net.CosmosDb/commit/220a58a98e6c9dcf14d9557fdc4973cdf36ed03d, can that be considered as a fix for  bug #30 ?

**Comment by BenjaBobs** [comment]
I suggest writing a test that proves it works and then submitting a new pr.
Also, @evo-terren maybe you should set up some CI to do run tests on pr's. I know that [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/) is free for open source projects, and so is [AppVeyor](https://www.appveyor.com/pricing/).

**Comment by vemuripavan** [comment]
@BenjaBobs  sure, Thank you

**Pull request closed without merging**
